const CATALOG_DATA = {
  "whatsapp": "573143358926",
  "social": {
    "facebook":  "https://www.facebook.com/share/1NDSEfXYeV/",
    "instagram": "https://www.instagram.com/consentido303?igsh=ODNya3N6ZzNsdGZn",
    "tiktok":    "https://www.tiktok.com/@perfilconsentido?_r=1&_t=ZS-95rlCgVBf29"
  },
  "categories": [
    { "id": "juguetes",      "label": "💕 Juguetes",        "title": "Juguetes para Parejas" },
    { "id": "masturbadores", "label": "🥚 Masturbadores",   "title": "Masturbadores & Fundas" },
    { "id": "lubricantes",   "label": "💧 Lubricantes",     "title": "Lubricantes" },
    { "id": "aceites",       "label": "🌹 Aceites",         "title": "Aceites para Masajes" },
    { "id": "masajes",       "label": "🕯️ Velas & Masajes", "title": "Velas & Masajes" },
    { "id": "potenciadores", "label": "⚡ Potenciadores",   "title": "Potenciadores" },
    { "id": "juegos",        "label": "🎲 Juegos",          "title": "Juegos Eróticos" },
    { "id": "lenceria",      "label": "👙 Lencería",        "title": "Lencería & BDSM" },
    { "id": "belleza",       "label": "💄 Belleza",         "title": "Belleza & Cuidado" },
    { "id": "accesorios",    "label": "🌸 Accesorios",      "title": "Accesorios Sensuales" }
  ],
  "products": [
    { "sku": "CON-0001", "name": "Mini bala vibrador", "description": "Vibrador tipo bala", "price": 21000, "stock": 6, "catalogCategory": "juguetes", "emoji": "💕", "badge": null, "image": "mini-bala-vibradora.png" },
    { "sku": "CON-0002", "name": "Anillo vibrador", "description": "Anillo con vibración", "price": 12000, "stock": 10, "catalogCategory": "juguetes", "emoji": "💍", "badge": null },
    { "sku": "CON-0003", "name": "Vibrador Teseo pilot", "description": null, "price": 32000, "stock": 2, "catalogCategory": "juguetes", "emoji": "🔮", "badge": null, "image": "dildo-Teseo.png" },
    { "sku": "CON-0004", "name": "Vibrador Hot (Hitachi Magic)", "description": null, "price": 110000, "stock": 1, "catalogCategory": "juguetes", "emoji": "✨", "badge": "Best Seller", "image": "hitachi.png" },
    { "sku": "CON-0005", "name": "Vibrador We Love (Succionador Nyla)", "description": "Succionador", "price": 85000, "stock": 1, "catalogCategory": "juguetes", "emoji": "💜", "badge": null, "image": "succionador.png" },
    { "sku": "CON-0006", "name": "Vibrador Wonderful (labial discreto)", "description": "Vibrador con apariencia de labial", "price": 28000, "stock": 2, "catalogCategory": "juguetes", "emoji": "💋", "badge": null, "image": "labial-fake.png" },
    { "sku": "CON-0007", "name": "Plug silicona Talla S", "description": null, "price": 35000, "stock": 1, "catalogCategory": "juguetes", "emoji": "🌸", "badge": null, "image": "plug-silicona.png" },
    { "sku": "CON-0008", "name": "Plug metálico Talla S", "description": null, "price": 35000, "stock": 1, "catalogCategory": "juguetes", "emoji": "🌹", "badge": null, "image": "plug-metalico.png" },
    { "sku": "CON-0013", "name": "Kit salvavidas", "description": null, "price": 48000, "stock": 2, "catalogCategory": "juguetes", "emoji": "🎁", "badge": "Popular" },
    { "sku": "CON-0014", "name": "Perlas Ball Exotic", "description": "Perlas rellenas de aceite que se revientan con el calor", "price": 20000, "stock": 2, "catalogCategory": "juguetes", "emoji": "🫧", "badge": null },
    { "sku": "CON-0116", "name": "Bala Vibradora Yeain App", "description": null, "price": 75000, "stock": 1, "catalogCategory": "juguetes", "emoji": "📱", "badge": null, "image": "jug-bala-insertar.png" },
    { "sku": "CON-0117", "name": "Bala Pene Aplicación", "description": null, "price": 85000, "stock": 3, "catalogCategory": "juguetes", "emoji": "📲", "badge": null, "image": "jug-bala-pene.png" },
    { "sku": "CON-0120", "name": "Vibrador Hitachi Grande", "description": null, "price": 85000, "stock": 1, "catalogCategory": "juguetes", "emoji": "✨", "badge": null, "image": "hitachi.png" },
    { "sku": "CON-0125", "name": "Vibrador Forma U Aplicación", "description": null, "price": 130000, "stock": 2, "catalogCategory": "juguetes", "emoji": "🔱", "badge": null, "image": "jug-u.png" },
    { "sku": "CON-0164", "name": "Plug Metálico Talla M", "description": null, "price": 40000, "stock": 1, "catalogCategory": "juguetes", "emoji": "🌹", "badge": null, "image": "plug-metalico.png" },

    { "sku": "CON-0114", "name": "Funda Pene", "description": null, "price": 25000, "stock": 2, "catalogCategory": "masturbadores", "emoji": "🍆", "badge": null },
    { "sku": "CON-0115", "name": "Masturbador Masculino", "description": null, "price": 25000, "stock": 3, "catalogCategory": "masturbadores", "emoji": "🥚", "badge": null },
    { "sku": "CON-0121", "name": "Masturbador Lilith", "description": null, "price": 50000, "stock": 2, "catalogCategory": "masturbadores", "emoji": "🌙", "badge": null, "image": "msturbador-lust.png" },
    { "sku": "CON-0122", "name": "Huevo Masturbador", "description": null, "price": 15000, "stock": 5, "catalogCategory": "masturbadores", "emoji": "🥚", "badge": null },
    { "sku": "CON-0123", "name": "Kit Funda Pene", "description": null, "price": 13000, "stock": 2, "catalogCategory": "masturbadores", "emoji": "🎁", "badge": null },
    { "sku": "CON-0130", "name": "Funda Pene Stretchy", "description": null, "price": 29000, "stock": 6, "catalogCategory": "masturbadores", "emoji": "🍆", "badge": null },
    { "sku": "CON-0132", "name": "Funda Pene Vibración", "description": null, "price": 15000, "stock": 2, "catalogCategory": "masturbadores", "emoji": "✨", "badge": null },
    { "sku": "CON-0133", "name": "Kit Funda Dedos", "description": null, "price": 13000, "stock": 3, "catalogCategory": "masturbadores", "emoji": "🖐️", "badge": null },

    { "sku": "CON-0083", "name": "Lubricante Sex Love 10ml", "description": null, "price": 8000, "stock": 50, "catalogCategory": "lubricantes", "emoji": "💧", "badge": "Popular" },
    { "sku": "CON-0023", "name": "Lubricante Sex Love 120ml Neutro (vaginal)", "description": null, "price": 25000, "stock": 2, "catalogCategory": "lubricantes", "emoji": "💧", "badge": null },
    { "sku": "CON-0024", "name": "Lubricante Sex Love 120ml Íntimo (Anal)", "description": null, "price": 31000, "stock": 2, "catalogCategory": "lubricantes", "emoji": "💧", "badge": null },
    { "sku": "CON-0025", "name": "Lubricante Caliente Sex Love 30ml", "description": null, "price": 15000, "stock": 4, "catalogCategory": "lubricantes", "emoji": "🔥", "badge": null },
    { "sku": "CON-0026", "name": "Lubricante Cannabis Sex Love 30ml", "description": null, "price": 15000, "stock": 4, "catalogCategory": "lubricantes", "emoji": "🌿", "badge": null, "image": "lub-canabis.png" },
    { "sku": "CON-0033", "name": "Lubricante Electrizante Sex Love 37ml", "description": null, "price": 25000, "stock": 2, "catalogCategory": "lubricantes", "emoji": "⚡", "badge": null, "image": "lub-electriz-sexlove.png" },
    { "sku": "CON-0034", "name": "Lubricante Sex Love con dados 38ml", "description": null, "price": 25000, "stock": 2, "catalogCategory": "lubricantes", "emoji": "🎲", "badge": "Popular" },
    { "sku": "CON-0038", "name": "Lubricante Elixir 30ml Fresa bombón", "description": null, "price": 28000, "stock": 1, "catalogCategory": "lubricantes", "emoji": "🍓", "badge": null, "image": "lub-sabores30ml.png" },
    { "sku": "CON-0039", "name": "Lubricante Elixir 30ml Sandía", "description": null, "price": 28000, "stock": 1, "catalogCategory": "lubricantes", "emoji": "🍉", "badge": null, "image": "lub-sabores30ml.png" },
    { "sku": "CON-0040", "name": "Lubricante Elixir 30ml Whisky", "description": null, "price": 28000, "stock": 1, "catalogCategory": "lubricantes", "emoji": "🥃", "badge": null, "image": "lub-sabores30ml.png" },
    { "sku": "CON-0063", "name": "Lubricante Sen Íntimo 7ml Chocolate", "description": null, "price": 12000, "stock": 2, "catalogCategory": "lubricantes", "emoji": "🍫", "badge": null, "image": "sen-sachet7ml.png" },
    { "sku": "CON-0064", "name": "Lubricante Sen Íntimo 7ml Whisky", "description": null, "price": 12000, "stock": 5, "catalogCategory": "lubricantes", "emoji": "🥃", "badge": null, "image": "sen-sachet7ml.png" },
    { "sku": "CON-0065", "name": "Lubricante Sen Íntimo 7ml Caramelo", "description": null, "price": 12000, "stock": 0, "catalogCategory": "lubricantes", "emoji": "🍬", "badge": null, "image": "sen-sachet7ml.png" },
    { "sku": "CON-0084", "name": "Lubricante Sen Íntimo 7ml Neutro", "description": null, "price": 12000, "stock": 8, "catalogCategory": "lubricantes", "emoji": "💧", "badge": null, "image": "sen-sachet7ml.png" },
    { "sku": "CON-0053", "name": "Lubricante Sen Íntimo 30ml Café Moka", "description": null, "price": 31000, "stock": 2, "catalogCategory": "lubricantes", "emoji": "☕", "badge": null, "image": "sen-cafe.png" },
    { "sku": "CON-0054", "name": "Lubricante Sen Íntimo 30ml Whisky", "description": null, "price": 31000, "stock": 2, "catalogCategory": "lubricantes", "emoji": "🥃", "badge": null, "image": "sen-wisky.png" },
    { "sku": "CON-0055", "name": "Lubricante Sen Íntimo 30ml Chocolate", "description": null, "price": 31000, "stock": 1, "catalogCategory": "lubricantes", "emoji": "🍫", "badge": null, "image": "sen-chocolate.png" },
    { "sku": "CON-0056", "name": "Lubricante Sen Íntimo 30ml Neutro", "description": null, "price": 32000, "stock": 1, "catalogCategory": "lubricantes", "emoji": "💧", "badge": null, "image": "sen-neutro.png" },
    { "sku": "CON-0057", "name": "Lubricante Sen Íntimo 30ml Multiorgasmos", "description": null, "price": 44000, "stock": 2, "catalogCategory": "lubricantes", "emoji": "🌟", "badge": null, "image": "sen-multio.png" },
    { "sku": "CON-0058", "name": "Lubricante Sen Íntimo 30ml Frío/Calor", "description": null, "price": 50000, "stock": 2, "catalogCategory": "lubricantes", "emoji": "🌡️", "badge": null, "image": "sen-frio-calor.png" },
    { "sku": "CON-0059", "name": "Lubricante Sen Íntimo 30ml Anal", "description": null, "price": 46000, "stock": 1, "catalogCategory": "lubricantes", "emoji": "💧", "badge": null, "image": "sen-lub-anal.png" },
    { "sku": "CON-0060", "name": "Lubricante Sen Íntimo 30ml Estrechante", "description": null, "price": 46000, "stock": 3, "catalogCategory": "lubricantes", "emoji": "💫", "badge": null, "image": "sen-estrechante.png" },
    { "sku": "CON-0061", "name": "Lubricante Sen Íntimo 30ml Garganta profunda", "description": null, "price": 46000, "stock": 1, "catalogCategory": "lubricantes", "emoji": "💋", "badge": null, "image": "sen-garganta.png" },
    { "sku": "CON-0062", "name": "Lubricante Sen Íntimo 5ml Electrizante", "description": "Vibrador líquido", "price": 46000, "stock": 1, "catalogCategory": "lubricantes", "emoji": "⚡", "badge": null, "image": "sen-vibrador-liquido.png" },
    { "sku": "CON-0143", "name": "Lubricante Estrés Sen 7ml", "description": null, "price": 11000, "stock": 3, "catalogCategory": "lubricantes", "emoji": "💧", "badge": null, "image": "sen-sachet7ml.png" },
    { "sku": "CON-0144", "name": "Lubricante Multiorgasmos Sen 7ml", "description": null, "price": 11000, "stock": 4, "catalogCategory": "lubricantes", "emoji": "🌟", "badge": null, "image": "sen-sachet7ml.png" },
    { "sku": "CON-0145", "name": "Lubricante Anal Sen 7ml", "description": null, "price": 10000, "stock": 4, "catalogCategory": "lubricantes", "emoji": "💧", "badge": null, "image": "sen-sachet7ml.png" },
    { "sku": "CON-0146", "name": "Lubricante Anal Electrizante Sen 7ml", "description": null, "price": 12000, "stock": 4, "catalogCategory": "lubricantes", "emoji": "⚡", "badge": null, "image": "sen-sachet7ml.png" },
    { "sku": "CON-0147", "name": "Lubricante Placer 3ml", "description": null, "price": 12000, "stock": 8, "catalogCategory": "lubricantes", "emoji": "💕", "badge": null, "image": "lub-placer-3ml.png" },
    { "sku": "CON-0148", "name": "Lubricante Kamagel 10ml", "description": null, "price": 8000, "stock": 8, "catalogCategory": "lubricantes", "emoji": "💧", "badge": null },

    { "sku": "CON-0066", "name": "Aceite corporal Natural Sant 250ml Uva", "description": null, "price": 22000, "stock": 1, "catalogCategory": "aceites", "emoji": "🍇", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0067", "name": "Aceite corporal Natural Sant 250ml Coco", "description": null, "price": 22000, "stock": 1, "catalogCategory": "aceites", "emoji": "🥥", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0068", "name": "Aceite corporal Natural Sant 250ml Cannabis", "description": null, "price": 22000, "stock": 1, "catalogCategory": "aceites", "emoji": "🌿", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0069", "name": "Aceite corporal Natural Sant 250ml Café", "description": null, "price": 22000, "stock": 1, "catalogCategory": "aceites", "emoji": "☕", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0070", "name": "Aceite corporal Natural Sant 250ml Romero", "description": null, "price": 22000, "stock": 1, "catalogCategory": "aceites", "emoji": "🌿", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0071", "name": "Aceite corporal Natural Sant 250ml Rosa mosqueta", "description": null, "price": 22000, "stock": 1, "catalogCategory": "aceites", "emoji": "🌹", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0072", "name": "Aceite corporal Natural Sant 250ml Almendras", "description": null, "price": 22000, "stock": 1, "catalogCategory": "aceites", "emoji": "🌰", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0073", "name": "Aceite corporal Natural Sant 250ml Caléndula", "description": null, "price": 22000, "stock": 1, "catalogCategory": "aceites", "emoji": "🌼", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0074", "name": "Aceite corporal Natural Sant 250ml Naranja", "description": null, "price": 22000, "stock": 1, "catalogCategory": "aceites", "emoji": "🍊", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0075", "name": "Aceite corporal Natural Sant 120ml Uva", "description": null, "price": 13000, "stock": 2, "catalogCategory": "aceites", "emoji": "🍇", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0076", "name": "Aceite corporal Natural Sant 120ml Coco", "description": null, "price": 13000, "stock": 1, "catalogCategory": "aceites", "emoji": "🥥", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0077", "name": "Aceite corporal Natural Sant 120ml Naranja", "description": null, "price": 13000, "stock": 3, "catalogCategory": "aceites", "emoji": "🍊", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0078", "name": "Aceite corporal Natural Sant 120ml Romero", "description": null, "price": 13000, "stock": 1, "catalogCategory": "aceites", "emoji": "🌿", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0079", "name": "Aceite corporal Natural Sant 120ml Rosa mosqueta", "description": null, "price": 13000, "stock": 3, "catalogCategory": "aceites", "emoji": "🌹", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0080", "name": "Aceite corporal Natural Sant 120ml Café", "description": null, "price": 13000, "stock": 2, "catalogCategory": "aceites", "emoji": "☕", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0081", "name": "Aceite corporal Natural Sant 120ml Caléndula", "description": null, "price": 13000, "stock": 3, "catalogCategory": "aceites", "emoji": "🌼", "badge": null, "image": "aceitesCorporales.png" },
    { "sku": "CON-0082", "name": "Aceite corporal Natural Sant 120ml Almendras", "description": null, "price": 13000, "stock": 3, "catalogCategory": "aceites", "emoji": "🌰", "badge": null, "image": "aceitesCorporales.png" },

    { "sku": "CON-0041", "name": "Crema nutritiva vela Sex Love Yerbabuena", "description": null, "price": 24000, "stock": 1, "catalogCategory": "masajes", "emoji": "🌿", "badge": null, "image": "vela-masajes.png" },
    { "sku": "CON-0042", "name": "Crema nutritiva vela Sex Love Volcano Ice", "description": null, "price": 24000, "stock": 0, "catalogCategory": "masajes", "emoji": "❄️", "badge": null, "image": "vela-masajes.png" },
    { "sku": "CON-0043", "name": "Crema nutritiva vela Sex Love Coffee Delight", "description": null, "price": 24000, "stock": 1, "catalogCategory": "masajes", "emoji": "☕", "badge": null, "image": "vela-masajes.png" },
    { "sku": "CON-0044", "name": "Crema nutritiva vela Sex Love Frutos rojos", "description": null, "price": 24000, "stock": 1, "catalogCategory": "masajes", "emoji": "🍓", "badge": null, "image": "vela-masajes.png" },
    { "sku": "CON-0045", "name": "Crema nutritiva vela Sex Love Baileys", "description": null, "price": 24000, "stock": 1, "catalogCategory": "masajes", "emoji": "🥃", "badge": null, "image": "vela-masajes.png" },
    { "sku": "CON-0046", "name": "Crema corporal Sex Love 30g Clarifier", "description": null, "price": 23000, "stock": 1, "catalogCategory": "masajes", "emoji": "🌸", "badge": null },
    { "sku": "CON-0047", "name": "Crema Sex Love 5gr Multi Orgasmo", "description": null, "price": 9000, "stock": 5, "catalogCategory": "masajes", "emoji": "🌟", "badge": "Popular" },
    { "sku": "CON-0048", "name": "Crema Sex Love 5gr Fusion", "description": null, "price": 9000, "stock": 5, "catalogCategory": "masajes", "emoji": "✨", "badge": null },
    { "sku": "CON-0049", "name": "Crema Sex Love 5gr Strech", "description": null, "price": 9000, "stock": 5, "catalogCategory": "masajes", "emoji": "💫", "badge": null },
    { "sku": "CON-0050", "name": "Vela Sen Íntimo para masajes Sensual D", "description": null, "price": 40000, "stock": 2, "catalogCategory": "masajes", "emoji": "🕯️", "badge": null, "image": "sen-vela.png" },
    { "sku": "CON-0151", "name": "Mantequilla Corporal", "description": null, "price": 18000, "stock": 4, "catalogCategory": "masajes", "emoji": "🧈", "badge": null },
    { "sku": "CON-0152", "name": "Truly", "description": null, "price": 45000, "stock": 4, "catalogCategory": "masajes", "emoji": "🌿", "badge": null, "image": "truly.png" },
    { "sku": "CON-0153", "name": "Kit Truly", "description": null, "price": 85000, "stock": 1, "catalogCategory": "masajes", "emoji": "🎁", "badge": null },

    { "sku": "CON-0010", "name": "Powers X", "description": "Potenciador", "price": 10000, "stock": 38, "catalogCategory": "potenciadores", "emoji": "💪", "badge": "Popular" },
    { "sku": "CON-0011", "name": "Meromacho", "description": "Potenciador masculino", "price": 6000, "stock": 9, "catalogCategory": "potenciadores", "emoji": "🔥", "badge": "Popular" },
    { "sku": "CON-0111", "name": "Potenciador X Bull Fem", "description": "Potenciador femenino", "price": 11000, "stock": 4, "catalogCategory": "potenciadores", "emoji": "⚡", "badge": null },
    { "sku": "CON-0112", "name": "Potenciador X Bull Masculino", "description": "Potenciador masculino", "price": 9000, "stock": 3, "catalogCategory": "potenciadores", "emoji": "💪", "badge": null },
    { "sku": "CON-0113", "name": "Potenciador Gomas Kiéreme", "description": null, "price": 20000, "stock": 4, "catalogCategory": "potenciadores", "emoji": "🍬", "badge": null },
    { "sku": "CON-0149", "name": "Retardante Rino Splash", "description": null, "price": 15000, "stock": 2, "catalogCategory": "potenciadores", "emoji": "🦏", "badge": null, "image": "rino-spray.png" },
    { "sku": "CON-0150", "name": "Retardante Caballo Splash", "description": null, "price": 15000, "stock": 2, "catalogCategory": "potenciadores", "emoji": "🐎", "badge": null, "image": "caballo-spray.png" },

    { "sku": "CON-0100", "name": "Cartas Mística", "description": null, "price": 25000, "stock": 2, "catalogCategory": "juegos", "emoji": "🔮", "badge": null },
    { "sku": "CON-0101", "name": "Escalerita Tentación", "description": null, "price": 45000, "stock": 1, "catalogCategory": "juegos", "emoji": "🪜", "badge": null },
    { "sku": "CON-0102", "name": "Jenga Hot", "description": null, "price": 65000, "stock": 3, "catalogCategory": "juegos", "emoji": "🧱", "badge": "Popular" },
    { "sku": "CON-0103", "name": "Uno X", "description": null, "price": 20000, "stock": 5, "catalogCategory": "juegos", "emoji": "🃏", "badge": null },
    { "sku": "CON-0104", "name": "Cartas Fiesta", "description": null, "price": 36000, "stock": 1, "catalogCategory": "juegos", "emoji": "🎉", "badge": null },
    { "sku": "CON-0105", "name": "Cartas Verdad o se Atreve", "description": null, "price": 36000, "stock": 1, "catalogCategory": "juegos", "emoji": "🎴", "badge": null },
    { "sku": "CON-0106", "name": "Pirinolas", "description": null, "price": 12000, "stock": 4, "catalogCategory": "juegos", "emoji": "🌀", "badge": null },
    { "sku": "CON-0107", "name": "Dados Eróticos", "description": null, "price": 13000, "stock": 4, "catalogCategory": "juegos", "emoji": "🎲", "badge": null },

    { "sku": "CON-0118", "name": "Media Malla", "description": null, "price": 15000, "stock": 3, "catalogCategory": "lenceria", "emoji": "🧦", "badge": null },
    { "sku": "CON-0124", "name": "Media Liguero", "description": null, "price": 12000, "stock": 3, "catalogCategory": "lenceria", "emoji": "👠", "badge": null },
    { "sku": "CON-0126", "name": "Kit con Esposas", "description": null, "price": 45000, "stock": 3, "catalogCategory": "lenceria", "emoji": "🔗", "badge": null },
    { "sku": "CON-0127", "name": "Lencería", "description": null, "price": 68000, "stock": 10, "catalogCategory": "lenceria", "emoji": "👙", "badge": null },
    { "sku": "CON-0128", "name": "Lencería Sencilla", "description": null, "price": 45000, "stock": 6, "catalogCategory": "lenceria", "emoji": "👙", "badge": null },
    { "sku": "CON-0129", "name": "Disfraz Sexy", "description": null, "price": 50000, "stock": 2, "catalogCategory": "lenceria", "emoji": "🎭", "badge": null },
    { "sku": "CON-0131", "name": "Esposas Metálicas", "description": null, "price": 15000, "stock": 3, "catalogCategory": "lenceria", "emoji": "🔗", "badge": null },
    { "sku": "CON-0134", "name": "Pezoneros", "description": null, "price": 12000, "stock": 4, "catalogCategory": "lenceria", "emoji": "🌸", "badge": null },
    { "sku": "CON-0136", "name": "Esposas Cuero", "description": null, "price": 30000, "stock": 4, "catalogCategory": "lenceria", "emoji": "⛓️", "badge": null },
    { "sku": "CON-0137", "name": "Látigos", "description": null, "price": 25000, "stock": 2, "catalogCategory": "lenceria", "emoji": "🪢", "badge": null },
    { "sku": "CON-0138", "name": "Arnés Pies y Manos", "description": null, "price": 65000, "stock": 1, "catalogCategory": "lenceria", "emoji": "⛓️", "badge": null },
    { "sku": "CON-0139", "name": "Arnés Cola", "description": null, "price": 80000, "stock": 2, "catalogCategory": "lenceria", "emoji": "🐰", "badge": null },
    { "sku": "CON-0140", "name": "Body con Brillos Bordó", "description": null, "price": 35000, "stock": 1, "catalogCategory": "lenceria", "emoji": "✨", "badge": null },
    { "sku": "CON-0141", "name": "Body Bordó / Fashion", "description": null, "price": 30000, "stock": 2, "catalogCategory": "lenceria", "emoji": "👗", "badge": null },
    { "sku": "CON-0142", "name": "Antifaz Pluma", "description": null, "price": 20000, "stock": 3, "catalogCategory": "lenceria", "emoji": "🎭", "badge": null },

    { "sku": "CON-0154", "name": "Kit Labios", "description": null, "price": 23000, "stock": 3, "catalogCategory": "belleza", "emoji": "💋", "badge": null },
    { "sku": "CON-0155", "name": "Kit Cejas y Pestañas", "description": null, "price": 18000, "stock": 3, "catalogCategory": "belleza", "emoji": "👁️", "badge": null },
    { "sku": "CON-0156", "name": "Mascarillas", "description": null, "price": 2500, "stock": 8, "catalogCategory": "belleza", "emoji": "🧖", "badge": null },
    { "sku": "CON-0157", "name": "Splash Capilar", "description": null, "price": 17000, "stock": 4, "catalogCategory": "belleza", "emoji": "💆", "badge": null },
    { "sku": "CON-0158", "name": "Desmaquillador", "description": null, "price": 22000, "stock": 2, "catalogCategory": "belleza", "emoji": "🧴", "badge": null },
    { "sku": "CON-0159", "name": "Espuma Facial", "description": null, "price": 23000, "stock": 2, "catalogCategory": "belleza", "emoji": "🫧", "badge": null },
    { "sku": "CON-0160", "name": "Gloss Brillo", "description": null, "price": 7000, "stock": 25, "catalogCategory": "belleza", "emoji": "💄", "badge": "Popular" },
    { "sku": "CON-0161", "name": "Pestañina", "description": null, "price": 23000, "stock": 3, "catalogCategory": "belleza", "emoji": "👁️", "badge": null },
    { "sku": "CON-0162", "name": "Pañitos Húmedos Faciales", "description": null, "price": 5000, "stock": 16, "catalogCategory": "belleza", "emoji": "🧻", "badge": null },
    { "sku": "CON-0163", "name": "Colágeno Labios", "description": null, "price": 1500, "stock": 3, "catalogCategory": "belleza", "emoji": "💋", "badge": null },

    { "sku": "CON-0012", "name": "Blow Pop Polvos explosivos", "description": null, "price": 5000, "stock": 28, "catalogCategory": "accesorios", "emoji": "🎆", "badge": null },
    { "sku": "CON-0016", "name": "Uro OT Probiótico Vaginal", "description": "Probiótico vaginal", "price": 56000, "stock": 7, "catalogCategory": "accesorios", "emoji": "🌸", "badge": null },
    { "sku": "CON-0036", "name": "Loción Splash Feromonas Sex Love Adán 40ml", "description": null, "price": 21000, "stock": 5, "catalogCategory": "accesorios", "emoji": "🌺", "badge": null, "image": "adan.png" },
    { "sku": "CON-0037", "name": "Loción Splash Feromonas Sex Love Eva 35ml", "description": null, "price": 21000, "stock": 8, "catalogCategory": "accesorios", "emoji": "🌸", "badge": null, "image": "eva.png" },
    { "sku": "CON-0051", "name": "Brillo labial Sen Íntimo con feromonas", "description": "Brillo labial con feromonas", "price": 35000, "stock": 1, "catalogCategory": "accesorios", "emoji": "💋", "badge": null, "image": "sen-brillo.png" },
    { "sku": "CON-0052", "name": "Toy Cleaner Sen Íntimo 30ml", "description": "Limpiador de juguetes", "price": 18000, "stock": 2, "catalogCategory": "accesorios", "emoji": "🧴", "badge": null },
    { "sku": "CON-0108", "name": "Condones +Sex", "description": null, "price": 5000, "stock": 20, "catalogCategory": "accesorios", "emoji": "🛡️", "badge": null },
    { "sku": "CON-0119", "name": "Gomas Interior Comestible", "description": null, "price": 29000, "stock": 5, "catalogCategory": "accesorios", "emoji": "🍬", "badge": null },
    { "sku": "CON-0135", "name": "Condones Titanium", "description": null, "price": 5000, "stock": 5, "catalogCategory": "accesorios", "emoji": "🛡️", "badge": null }
  ]
};
